# Generated by Django 5.0.3 on 2025-01-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
