# Generated by Django 5.0.3 on 2025-01-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_transaction_payment_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cryptocurrency",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
