# Generated by Django 5.0.3 on 2025-01-30 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_cryptocurrency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
    ]
