# Generated by Django 5.0.3 on 2025-01-30 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_remove_order_payment_method"),
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="wallet",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="wallet.wallet",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["wallet"], name="orders_tran_wallet__fa953f_idx"),
        ),
    ]
