# Generated by Django 5.0.3 on 2025-04-11 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_alter_transaction_wallet"),
        ("smtp", "0005_smtp_hosting_smtp_location"),
        ("webmails", "0006_alter_webmail_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="smtp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="smtp.smtp",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="webmail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="webmails.webmail",
            ),
        ),
    ]
