# Generated by Django 5.0.3 on 2025-05-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_order_data_order_smtp_order_webmail"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_reserved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="reservation_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="reserved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
