# Generated by Django 5.0.3 on 2025-01-12 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="category",
            field=models.CharField(
                choices=[
                    ("email_marketing", "Email Marketing"),
                    ("webmail_business", "Webmail Business"),
                    ("marketing_tools", "Marketing Tools"),
                    ("hosting_domain", "Hosting Domain"),
                    ("games", "Games"),
                    ("graphic_developer", "Graphic Developer"),
                    ("vpn_socks_proxy", "VPN Socks Proxy"),
                    ("shopping", "Shopping"),
                    ("program", "Program"),
                    ("stream", "Stream"),
                    ("dating", "Dating"),
                    ("learning", "Learning"),
                    ("torent", "Torent"),
                    ("voip", "VOIP"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=255,
            ),
        ),
        migrations.RemoveField(
            model_name="accountdata",
            name="account",
        ),
        migrations.RenameField(
            model_name="account",
            old_name="location",
            new_name="country",
        ),
        migrations.RenameField(
            model_name="account",
            old_name="source",
            new_name="password",
        ),
        migrations.RenameField(
            model_name="account",
            old_name="website_domain",
            new_name="username",
        ),
        migrations.RenameIndex(
            model_name="account",
            new_name="accounts_ac_user_id_280436_idx",
            old_name="accounts_ac_user_id_c85660_idx",
        ),
        migrations.AddField(
            model_name="account",
            name="login_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="notes",
            field=models.TextField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="status",
            field=models.CharField(
                choices=[("sold", "Sold"), ("unsold", "Un Sold"), ("deleted", "Deleted")],
                default="unsold",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[("created", "Craeted"), ("hacked", "Hacked / Cracked")], default="created", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="proof",
            field=models.URLField(
                validators=[
                    django.core.validators.URLValidator(
                        regex="^https?:\\/\\/((?:vgy\\.me|prnt\\.sc|gyazo\\.com)\\/.*)"
                    )
                ]
            ),
        ),
        migrations.DeleteModel(
            name="AccountCategory",
        ),
        migrations.DeleteModel(
            name="AccountData",
        ),
    ]
