# Generated by Django 5.0.3 on 2025-01-12 22:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_account_category_remove_accountdata_account_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="login_url",
            new_name="domain",
        ),
    ]
