# Generated by Django 5.0.3 on 2025-05-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_account_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
