volumes:
  ra3d_postgres_data: {}
  ra3d_postgres_data_backups: {}
  ra3d_django_media: {}
  ra3d_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: ra3d_django
    container_name: ra3d_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.django
      - ./.envs/.env
      - ./.envs/.postgres
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: ra3d_production_postgres
    container_name: ra3d_postgres
    volumes:
      - ra3d_postgres_data:/var/lib/postgresql/data
      - ra3d_postgres_data_backups:/backups
    env_file:
      - ./.envs/.postgres

  redis:
    image: "redis:alpine"
    container_name: ra3d_redis
    ports:
      - "6379:6379"
    volumes:
      - ra3d_redis_data:/data
    command: redis-server --save 900 1 --save 300 10 --save 60 10000 --appendonly yes
    restart: unless-stopped

  celeryworker:
    <<: *django
    image: ra3d_celeryworker
    container_name: ra3d_celeryworker
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker
