# Generated by Django 5.0.3 on 2025-01-17 20:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shell",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("shell_url", models.URLField(max_length=355)),
                (
                    "shell_type",
                    models.CharField(
                        choices=[("Created", "Created"), ("Hacked / Cracked", "Hacked / Cracked")],
                        default="Created",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Sold", "Sold"), ("Unsold", "Unsold"), ("Deleted", "Deleted")],
                        default="Unsold",
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="shells", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Shells",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["shell_url", "user"], name="shells_shel_shell_u_600dc1_idx")],
                "unique_together": {("shell_url", "user")},
            },
        ),
    ]
