# Generated by Django 5.0.3 on 2025-01-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shells", "0002_shell_ssl_shell_tld"),
    ]

    operations = [
        migrations.AddField(
            model_name="shell",
            name="details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
