# Generated by Django 5.0.3 on 2025-01-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shells", "0003_shell_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shell",
            name="tld",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
