# Generated by Django 5.0.3 on 2025-01-19 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shells", "0004_alter_shell_tld"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shell",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
