# Generated by Django 5.0.3 on 2025-03-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shells", "0005_alter_shell_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shell",
            name="shell_type",
            field=models.CharField(
                choices=[("Created", "Created"), ("Cracked", "Cracked")], default="Created", max_length=20
            ),
        ),
    ]
