# Generated by Django 5.0.3 on 2025-01-18 22:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CPanel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("ip", models.GenericIPAddressField()),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "cpanel_type",
                    models.CharField(
                        choices=[("Created", "Created"), ("Hacked / Cracked", "Hacked / Cracked")],
                        default="Created",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Sold", "Sold"), ("Unsold", "Unsold"), ("Deleted", "Deleted")],
                        default="Unsold",
                        max_length=255,
                    ),
                ),
                ("details", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cpanel", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "cPanels",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["ip", "user"], name="cpanel_cpan_ip_76d6fb_idx"),
                    models.Index(fields=["status"], name="cpanel_cpan_status_742885_idx"),
                    models.Index(fields=["created_at"], name="cpanel_cpan_created_12f813_idx"),
                ],
                "unique_together": {("ip", "user")},
            },
        ),
    ]
