# Generated by Django 5.0.3 on 2025-01-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpanel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpanel",
            name="ssl",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cpanel",
            name="tld",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="cpanel",
            name="ip",
            field=models.CharField(default="127.0.0.1", max_length=255),
        ),
    ]
