# Generated by Django 5.0.3 on 2025-01-19 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpanel", "0002_cpanel_ssl_cpanel_tld_alter_cpanel_ip"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cpanel",
            name="cpanel_cpan_ip_76d6fb_idx",
        ),
        migrations.RenameField(
            model_name="cpanel",
            old_name="ip",
            new_name="host",
        ),
        migrations.AlterUniqueTogether(
            name="cpanel",
            unique_together={("host", "user")},
        ),
        migrations.AddIndex(
            model_name="cpanel",
            index=models.Index(fields=["host", "user"], name="cpanel_cpan_host_35e42d_idx"),
        ),
    ]
