# Generated by Django 5.0.3 on 2025-01-19 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpanel", "0003_remove_cpanel_cpanel_cpan_ip_76d6fb_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cpanel",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
