# Generated by Django 5.0.3 on 2025-02-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpanel", "0004_alter_cpanel_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpanel",
            name="hosting",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cpanel",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
