# Generated by Django 5.0.3 on 2025-01-07 22:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadsCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Leads",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("niche", models.CharField(max_length=255)),
                ("website_domain", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("emails_number", models.IntegerField()),
                ("proof", models.FileField(upload_to="leads/proofs/")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_sold", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="leads", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="leads", to="leads.leadscategory"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadsData",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "data",
                    models.FileField(
                        upload_to="secret/leads/data/",
                        validators=[
                            django.core.validators.FileExtensionValidator(allowed_extensions=["txt", "pdf", "docx"])
                        ],
                    ),
                ),
                (
                    "leads",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="secret_data", to="leads.leads"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="leads",
            index=models.Index(fields=["user", "category"], name="leads_leads_user_id_f5df7f_idx"),
        ),
    ]
