# Generated by Django 5.0.3 on 2025-01-07 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leads",
            name="proof",
            field=models.FileField(
                upload_to="leads/proofs/",
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["txt", "pdf", "docx"])],
            ),
        ),
    ]
