# Generated by Django 5.0.3 on 2025-01-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_alter_leads_proof"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leads",
            name="password",
            field=models.BooleanField(default=False),
        ),
    ]
