# Generated by Django 5.0.3 on 2025-01-18 14:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rdp",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("ip", models.GenericIPAddressField()),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("ram_size", models.CharField(max_length=255)),
                ("cpu_cores", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "rdp_type",
                    models.CharField(
                        choices=[("Created", "Created"), ("Hacked / Cracked", "Hacked / Cracked")],
                        default="Created",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Sold", "Sold"), ("Unsold", "Unsold"), ("Deleted", "Deleted")],
                        default="Unsold",
                        max_length=255,
                    ),
                ),
                (
                    "windows_type",
                    models.CharField(
                        choices=[
                            ("Windows", "Windows"),
                            ("Win XP", "Win XP"),
                            ("Win Vista", "Win Vista"),
                            ("Win 2003", "Win 2003"),
                            ("Win 2008", "Win 2008"),
                            ("Win 7", "Win 7"),
                            ("Win 8", "Win 8"),
                            ("Win 10", "Win 10"),
                            ("Win Server 2012", "Win Server 2012"),
                            ("Win Server 2016", "Win Server 2016"),
                            ("Win Server 2019", "Win Server 2019"),
                            ("Win Server 2022", "Win Server 2022"),
                            ("Win Server 2025", "Win Server 2025"),
                            ("Other", "Other"),
                        ],
                        default="Windows",
                        max_length=255,
                    ),
                ),
                ("details", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rdps", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Rdps",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["ip", "user"], name="rdp_rdp_ip_1c8be3_idx"),
                    models.Index(fields=["status"], name="rdp_rdp_status_1d9bd9_idx"),
                    models.Index(fields=["created_at"], name="rdp_rdp_created_7b15c4_idx"),
                ],
                "unique_together": {("ip", "user")},
            },
        ),
    ]
