# Generated by Django 5.0.3 on 2025-01-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rdp", "0002_alter_rdp_cpu_cores_alter_rdp_ram_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="rdp",
            name="access_type",
            field=models.CharField(choices=[("Admin", "Admin"), ("User", "User")], default="User", max_length=255),
        ),
    ]
