# Generated by Django 5.0.3 on 2025-01-19 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rdp", "0003_rdp_access_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rdp",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
