# Generated by Django 5.0.3 on 2025-02-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rdp", "0004_alter_rdp_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="rdp",
            name="hosting",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rdp",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
