# Generated by Django 5.0.3 on 2025-01-07 22:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="businessdata",
            old_name="account",
            new_name="business",
        ),
    ]
