#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py makemigrations --noinput
python manage.py migrate --noinput
python manage.py collectstatic --noinput

# exec python manage.py runserver 0.0.0.0:8000

exec python -m uvicorn config.asgi:application --workers 17 --host 0.0.0.0 --port 8000 --log-level debug --reload
#  --workers 4 ("workers" flag is ignored when reloading is enabled.)
