# Generated by Django 5.0.3 on 2025-03-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuserprofile_email_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuserprofile",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
