# Generated by Django 5.0.3 on 2025-04-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuserprofile_email_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuserprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("MODERATOR", "Moderator"),
                    ("SELLER", "Seller"),
                    ("PENDING_SELLER", "Pending Seller"),
                    ("BUYER", "Buyer"),
                    ("SUPPORT", "Support"),
                    ("SUSPENDED", "Suspended"),
                    ("SELLER_SUSPENDED", "Seller Suspended"),
                ],
                default="BUYER",
                max_length=20,
            ),
        ),
    ]
