# Generated by Django 5.0.3 on 2025-01-17 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SMTP",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("ip", models.GenericIPAddressField()),
                ("port", models.IntegerField()),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                (
                    "smtp_type",
                    models.CharField(
                        choices=[("Created", "Created"), ("Hacked / Cracked", "Hacked / Cracked")], max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Sold", "Sold"), ("Unsold", "Unsold"), ("Deleted", "Deleted")], max_length=255
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="smtp", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "SMTP",
                "verbose_name_plural": "SMTPs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["ip", "port"], name="smtp_smtp_ip_a286f7_idx"),
                    models.Index(fields=["username"], name="smtp_smtp_usernam_30e988_idx"),
                ],
                "unique_together": {("ip", "port")},
            },
        ),
    ]
