# Generated by Django 5.0.3 on 2025-01-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smtp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smtp",
            name="smtp_type",
            field=models.CharField(
                choices=[("Created", "Created"), ("Hacked / Cracked", "Hacked / Cracked")],
                default="Created",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="smtp",
            name="status",
            field=models.CharField(
                choices=[("Sold", "Sold"), ("Unsold", "Unsold"), ("Deleted", "Deleted")],
                default="Unsold",
                max_length=255,
            ),
        ),
    ]
