# Generated by Django 5.0.3 on 2025-03-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smtp", "0003_alter_smtp_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smtp",
            name="smtp_type",
            field=models.CharField(
                choices=[("Created", "Created"), ("Cracked", "Cracked")], default="Created", max_length=255
            ),
        ),
    ]
