# Generated by Django 5.0.3 on 2025-03-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smtp", "0004_alter_smtp_smtp_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="smtp",
            name="hosting",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="smtp",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
