# Generated by Django 5.0.3 on 2025-05-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smtp", "0005_smtp_hosting_smtp_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="smtp",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
