# Generated by Django 5.0.3 on 2025-01-12 22:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebMail",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "source",
                    models.CharField(
                        choices=[("Created", "Created"), ("Hacked / Cracked", "Hacked / Cracked"), ("Logs", "Logs")],
                        default="Created",
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cPanel Webmail", "cPanel Webmail"),
                            ("GoDaddy Webmail", "GoDaddy Webmail"),
                            ("Office 365", "Office 365"),
                            ("Google Workspace", "Google Workspace"),
                            ("Zoho Mail", "Zoho Mail"),
                            ("Rackspace Email", "Rackspace Email"),
                            ("IONOS Webmail", "IONOS Webmail"),
                        ],
                        default="cPanel Webmail",
                        max_length=255,
                    ),
                ),
                (
                    "niche",
                    models.CharField(
                        choices=[
                            ("Real State", "Real State"),
                            ("Health - Fitness", "Health - Fitness"),
                            ("Hobbies - Interest", "Hobbies - Interest"),
                            ("Relationship - Dating", "Relationship - Dating"),
                            ("Wealth - Money", "Wealth - Money"),
                            ("Education", "Education"),
                            ("Prepping", "Prepping"),
                            ("Self-Improvement", "Self-Improvement"),
                            ("Wealth Building Through Investing", "Wealth Building Through Investing"),
                            ("Pets", "Pets"),
                            ("Beauty", "Beauty"),
                            ("Gadgets - Technology", "Gadgets - Technology"),
                            ("Personal Finance", "Personal Finance"),
                            ("Home Security", "Home Security"),
                            ("Babies", "Babies"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Sold", "Sold"), ("Unsold", "Unsold"), ("Deleted", "Deleted")],
                        default="Unsold",
                        max_length=255,
                    ),
                ),
                ("is_sold", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webmail",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["user", "category"], name="webmails_we_user_id_cf6129_idx")],
            },
        ),
    ]
