# Generated by Django 5.0.3 on 2025-01-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webmails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webmail",
            name="domain",
            field=models.URLField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
