# Generated by Django 5.0.3 on 2025-03-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webmails", "0003_alter_webmail_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webmail",
            name="source",
            field=models.CharField(
                choices=[("Created", "Created"), ("Cracked", "Cracked"), ("Logs", "Logs")],
                default="Created",
                max_length=255,
            ),
        ),
    ]
