# Generated by Django 5.0.3 on 2025-03-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webmails", "0004_alter_webmail_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="webmail",
            name="hosting",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webmail",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
