# Generated by Django 5.0.3 on 2025-03-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webmails", "0005_webmail_hosting_webmail_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webmail",
            name="domain",
            field=models.CharField(max_length=255),
        ),
    ]
