# Generated by Django 5.0.3 on 2025-05-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webmails", "0006_alter_webmail_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="webmail",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
